// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/gin-gonic/gin"

	"github.com/zhaoyunxing92/flexi-code/server/configs"
	"github.com/zhaoyunxing92/flexi-code/server/internal/controller"
	"github.com/zhaoyunxing92/flexi-code/server/internal/repo/datasheet"
	"github.com/zhaoyunxing92/flexi-code/server/internal/router"
	"github.com/zhaoyunxing92/flexi-code/server/internal/server"
	datasheet2 "github.com/zhaoyunxing92/flexi-code/server/internal/service/datasheet"
	"github.com/zhaoyunxing92/flexi-code/server/internal/storage"
)

// Injectors from wire.go:

// initApplication init application.
func initApplication(appConfig *configs.App, storageConfig *configs.Storage) (*gin.Engine, error) {
	storageStorage, err := storage.NewStorage(storageConfig)
	if err != nil {
		return nil, err
	}
	datasheetRepo := datasheet.NewDatasheetRepo(storageStorage)
	datasheetService := datasheet2.NewDatasheetService(datasheetRepo)
	datasheetCtrl := controller.NewDatasheetCtrl(datasheetService)
	routerRouter := router.NewRouter(datasheetCtrl)
	engine := server.NewHttpServer(routerRouter, appConfig)
	return engine, nil
}
